version: "3.9"
services:
  mongo:
    image: "mongo"
    container_name: "mongo"
    volumes:
      - ./database:/data/db
    ports:
      - 27017:27017
  ncaa:
    image: bobbyaray/ncaatourney:2023
    ports:
      - "80:80"
    environment:
      SPRING_DATA_MONGODB_HOST: "mongo"
    depends_on:
      - mongo